# Site settings
title: Streamer Guide
email: streamerguide@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Streamer Guide is a website that collects guides for streamers ranging
  from how to get started, and how to become professional.

baseurl: "" 
url: "http://streamerguide.com"

twitter_username: streamerguide
github_username:  streamer-guide

exclude:
    - README.md
    - Vagrantfile
    - CNAME

# Build settings
markdown: kramdown
